spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financial-records
    username: postgres
    password: 123
    driver : org.postgresql.Driver
  flyway:
    enabled: true
    baselineOnMigrate: true
  jpa:
    show-sql: true
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: true
    generate-ddl : true
    hibernate:
      ddl-auto : validate

